FINE_TO_PUBLIC_LABEL = {
    "person": "Other",
    "bottle": "Recycling",
    "wine glass": "Recycling",
    "cup": "Recycling",
    "fork": "Trash",
    "knife": "Trash",
    "spoon": "Trash",
    "bowl": "Recycling",
    "banana": "Trash",
    "apple": "Trash",
    "sandwich": "Trash",
    "orange": "Trash",
    "broccoli": "Trash",
    "carrot": "Trash",
    "hot dog": "Trash",
    "pizza": "Trash",
    "donut": "Trash",
    "cake": "Trash",
    "chair": "Other",
    "couch": "Other",
    "potted plant": "Other",
    "bed": "Other",
    "dining table": "Other",
    "toilet": "Other",
    "tv": "Other",
    "laptop": "Other",
    "mouse": "Other",
    "remote": "Other",
    "keyboard": "Other",
    "cell phone": "Other",
    "microwave": "Other",
    "oven": "Other",
    "toaster": "Other",
    "sink": "Other",
    "refrigerator": "Other",
    "book": "Recycling",
    "clock": "Other",
    "vase": "Other",
    "scissors": "Other",
    "teddy bear": "Other",
    "hair drier": "Other",
    "toothbrush": "Trash"
}